### ISSUE TITLE
Filling a blank map on the latest fabric 1.20.1 version crashes Minecraft instantly.

### ISSUE THREAD

**Issue by forgotmypancakes** [MehVahdJukaar/Moonlight#168] opened 2023-11-02 07:25 UTC
When filling a blank map in a single player world, the game freezes and stops responding. If on a server, the game hard crashes to desktop immediately. 

I have checked all my other mods and they work fine. What is the underlying issue?

**Comment by Xelbayria** [comment] 2023-11-02 08:54
What's the version of your moonlight? Can you check if you are using the latest version? 

Is this a question or reporting a bug?

**Comment by MehVahdJukaar** [comment] 2023-11-02 09:42
Send latest.log

**Comment by forgotmypancakes** [comment] 2023-11-02 17:21
> What's the version of your moonlight? Can you check if you are using the latest version?
> 
> Is this a question or reporting a bug?

Using the latest fabric version. I’ll upload the crash log and latest when I am off work today

**Comment by Xelbayria** [comment] 2023-11-02 19:26
Next time, you create a new issue, please use "Report Bug" and fill out the required Details. 

---

## Details: 
- Version-Loaders: 1.20.1-Fabric
- Moonlight Version: `moonlight-1.20-2.8.56-fabric`

**Comment by AaronKasai** [comment] 2023-11-05 07:40
Hi, sorry in advance if this is the wrong place.

I was taking a empty map or treasure map from a ship-wreck chest, can't recall the exact details, and the game crashed. Game now crashes every time I try to join the world.

I was using moonlight 1.20 2.8.53, fabric loader 1.20.1
I updated to moonlight 1.20 2.8.56, didn't fix it.

Reason I thought it could be related to this mod was due to this snippet from the crash report:

```
java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_330$class_331 failed
	at net.minecraft.class_330.method_32601(class_330.java:44)
	at net.minecraft.class_330.method_1769(class_330.java:36)
	at net.minecraft.class_634.mixinextras$bridge$method_1769$204(class_634.java)
	at net.minecraft.class_634.wrapOperation$zni000$moonlight$handleExtraData(class_634.java:5237)
	at net.minecraft.class_634.wrapOperation$zni000$moonlight$handleExtraData$mixinextras$bridge$203(class_634.java)
        ...
``` 

Removing moonlight (also removing supplementaries and dummmmy) allows me to join the world.

Apologies if its unrelated to this issue, or even this mod.
Let me know if you need anything else.

**Comment by Tehiyok** [comment] 2023-11-06 17:37
Hello, I apologize if I may be doing something wrong or if I would need to attach something, I am not accustomed to using GitHub.

I am encountering the same issue where I opened an ocean chest, looted a map, and the game instantly crashed. This occurs both when I play on my server and when I download the map and use it in singleplayer. I had previously used a version of this mod that was, I believe, two or three weeks older and updated to the newest version, but it did not resolve the problem.

The major challenge I face is that I am using the mod "supplementarys," which relies on MoonlightLib. Consequently, I cannot load the world without these two mods without potentially damaging my world.

Is there any solution or guidance you can provide to address this issue?

[crash-2023-11-06_18.35.26-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/13270648/crash-2023-11-06_18.35.26-client.txt)

**Comment by MehVahdJukaar** [comment] 2023-11-06 19:58
You sure you got latest moonlight?

**Comment by Tehiyok** [comment] 2023-11-06 20:07
Yup, I'm sure.

Fortunately, I had the bright idea to download the player data from my character, use NBTExplorer to delete the map from my inventory, and then upload the new player data to the server.
This resolved the problem.
The question now is whether the older Moonlight version corrupted the map, and the newer version simply couldn't handle it, or if the same issue persists in the newer version.

**Comment by AaronKasai** [comment] 2023-11-06 22:33
For clarity, I initially posted about my treasure map issue here, then hid it and created an issue on the Supplementries Git Repo.
https://github.com/MehVahdJukaar/Supplementaries/issues/824
I can reliably reproduce the issue using the versions I provide in the issue. Doesn't seem to just be something for older versions.

**Comment by MehVahdJukaar** [comment] 2023-11-07 01:40
closing this as it was a supplementaries issues with mixin plugin not being added properly and was fixed

**Closed as completed by MehVahdJukaar** 2023-11-07 01:40 UTC
Labels: bug, 1.20.1
