### ISSUE TITLE
rendering/ fluid issue?

### ISSUE THREAD

**Issue by border999** [MehVahdJukaar/Moonlight#80] opened 2023-01-29 17:40 UTC
[crash-2023-01-25_21.23.49-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/10530428/crash-2023-01-25_21.23.49-client.txt)

**Comment by border999** [comment] 2023-01-29 17:46
[crash-2023-01-29_12.44.31-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/10530437/crash-2023-01-29_12.44.31-server.txt)

**Comment by fuzzyweapon** [comment] 2023-01-30 02:22
Also experiencing this - 1.19.2 on Fabric SMP

**Comment by MehVahdJukaar** [comment] 2023-01-30 02:27
What fluid is that trying to render? None of my mods or mod that use this that you have add fluids and this mod doesn't appear anywhere in stack trace. Are you sure it's the cause?

**Comment by fuzzyweapon** [comment] 2023-01-30 02:48
I need to check the crash specifically as it might be a different bug >__>  If it doesn't match the server stack trace here, I will open a new bug.

**Comment by fuzzyweapon** [comment] 2023-01-30 03:04
Yeah I don't think mine is related to this so I put in a new issue at #81

**Comment by Xelbayria** [comment] 2023-10-18 21:36
is this issue related to #81?? and is it resolved?

**Comment by Xelbayria** [comment] 2023-12-26 00:59
Since there is no reply, i'll close this.

**Closed as completed by Xelbayria** 2023-12-26 00:59 UTC
Labels: bug, 1.19.2, FABRIC, FORGE
