### ISSUE TITLE
[🐞]: this.tab is null due one of modules having no setTabKey() = Related to EveryCompat

### ISSUE THREAD

**Issue by kerrschtein** [MehVahdJukaar/Moonlight#257] opened 2024-10-02 16:18 UTC
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

moonlight-1.20-2.13.2-fabric.jar

### Issue Detail

Crash upon opening.

### Log Attachment

[crash-2024-10-02_12.17.23-client.txt](https://github.com/user-attachments/files/17232785/crash-2024-10-02_12.17.23-client.txt)

**Comment by Xelbayria** [comment] 2024-10-02 19:31
it's a problem related to EveryCompat. I need you to find out which mod (Supported by EveryComp) is the cause of the problem.

**Comment by Xelbayria** [comment] 2024-10-03 01:13
If you have one of these 2 mods installed: 
- Beautiful Campfires
- Another Furniture

They both caused the crash because they are missing the tab stuff in the module. (fixed in v2.6.78)

**Comment by MehVahdJukaar** [comment] 2024-10-03 13:01
issue from EC

**Comment by Xelbayria** [comment] 2024-10-03 18:42
Should be fixed in v2.6.79 (Every Compat). This is not an issue related to moonlight. 

If you find another culprit that caused the crash. then please let me know. I can apply the fix

**Closed as completed by Xelbayria** 2024-10-03 18:42 UTC
Labels: 1.20.1, FABRIC, cause: EveryCompat
