### ISSUE TITLE
1.20.1 Refuses to load into world cause of this mod

### ISSUE THREAD

**Issue by ModernGamingWorld** [MehVahdJukaar/Moonlight#261] opened 2024-10-16 01:36 UTC
78: ASM: class com.minecolonies.core.event.ClientEventHandler onwWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
java.lang.RuntimeException: Not all required entries were found in datapack registry. How did this happen?Note that this could be caused by Paper or similar servers. Know that those are NOT meant to be used with mods
	at TRANSFORMER/supplementaries@1.20-2.8.17/net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkDatapackRegistry(VibeChecker.java:60)
	at TRANSFORMER/supplementaries@1.20-2.8.17/net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkVibe(VibeChecker.java:27)
	at TRANSFORMER/supplementaries@1.20-2.8.17/net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onServerTick(ServerEventsForge.java:228)
	at TRANSFORMER/supplementaries@1.20-2.8.17/net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onServerTick_LevelTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.11/net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:925)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.mdd58f72$dimthread$lambda$tickWorlds$0$b(MinecraftServer.java:9392)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:50)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.mdd58f72$dimthread$lambda$tickWorlds$1$a(MinecraftServer.java:9391)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:54)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Failed to get registry access: level was null
	at TRANSFORMER/moonlight@1.20-2.13.10/net.mehvahdjukaar.moonlight.api.util.Utils.hackyGetRegistryAccess(Utils.java:207)
	at TRANSFORMER/moonlight@1.20-2.13.10/net.mehvahdjukaar.moonlight.api.misc.DynamicHolder.getInstance(DynamicHolder.java:79)
	at TRANSFORMER/moonlight@1.20-2.13.10/net.mehvahdjukaar.moonlight.api.misc.DataObjectReference.getHolder(DataObjectReference.java:31)
	at TRANSFORMER/moonlight@1.20-2.13.10/net.mehvahdjukaar.moonlight.api.fluids.SoftFluidRegistry.getEmpty(SoftFluidRegistry.java:22)
	at TRANSFORMER/supplementaries@1.20-2.8.17/net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkDatapackRegistry(VibeChecker.java:58)
	... 15 more

**Comment by ModernGamingWorld** [comment] 2024-10-16 01:36
my whole log file is spammed with Your mod causing issues

**Comment by Xelbayria** [comment] 2024-10-16 03:19
You need to include the file, `latest.log`. just drag the file here and it will get uploaded. 

# EDIT: 
are you playing on server? if yes, then is Server via **Paper or similar servers**??  

if you are playing in Singleplayer world, then the latest.log is needed.

**Comment by ModernGamingWorld** [comment] 2024-10-16 04:36
[latest.log](https://github.com/user-attachments/files/17389249/latest.log)

**Comment by Xelbayria** [comment] 2024-10-16 05:05
can you answer my question in my previous post?

**Comment by ModernGamingWorld** [comment] 2024-10-16 05:44
Single player atm, I have an official server for my modpack, but once I could not log into single player. I downgraded the mod on server right away to prevent loss of data

**Comment by MehVahdJukaar** [comment] 2024-10-16 07:34
Does this happen with just the mod on?

**Comment by ModernGamingWorld** [comment] 2024-10-18 20:54
[latest.log](https://github.com/user-attachments/files/17440607/latest.log)

Updated, still not working @MehVahdJukaar. This time it crashed me straight to desktop using the latest version from today

I have over 500ish mods in my pack, I am not going to pull them all out to get your mod to work, as that would ruin my custom modpack as its a huge pack

**Comment by MehVahdJukaar** [comment] 2024-10-19 01:36
i have absolutely no clue how this could happen. All i know its likely caused by DimThread doing some stuff

**Comment by MehVahdJukaar** [comment] 2024-10-19 01:36
also you are not using latest version

**Comment by Xelbayria** [comment] 2024-11-11 07:20
@ModernGamingWorld have you resolved the issue?

**Comment by Xelbayria** [comment] 2024-11-20 10:08
Closing this due to no replying

**Closed as not planned by Xelbayria** 2024-11-20 10:08 UTC
Labels: bug, 1.20.1, FORGE
